name: Context Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  maintenance-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Context File Size
        run: |
          for file in $(find .vscode/copilot -name "*.json"); do
            size=$(stat -f%z "$file")
            if [ $size -gt 1000000 ]; then
              echo "::warning::Context file $file is large (${size}b), consider archiving old content"
            fi
          done

      - name: Check Orphaned Threads
        run: |
          for file in $(find .vscode/copilot/contexts -name "*.json"); do
            if ! jq -e '.metadata.conversationHistory.parentId' "$file" > /dev/null; then
              echo "::warning::Orphaned thread found in $file"
            fi
          done

      - name: Check Stale Decisions
        run: |
          threshold_date=$(date -d "6 months ago" +%s)
          for file in $(find .vscode/copilot -name "*.json"); do
            if jq -e --arg date $threshold_date '.designDecisions.architecture[] |
              select((.madeAt | fromdateiso8601) < ($date | tonumber))' "$file" > /dev/null; then
              echo "::warning::Old design decisions found in $file, consider reviewing"
            fi
          done
